In [2]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
#import seaborn as se

ModuleNotFoundError: No module named 'seaborn'

In [18]:
# Calculate Variance
def cal_variance(a):
    '''
    Input : a is dxd numpy matrix
    Output : A variance vector of dimention d
    '''
    n,d = np.shape(a)
    mean_matrix = np.ones((n,d)) * cal_mean(a)
    variance =(1/n)* np.diag(np.transpose(a-mean_matrix).dot(a-mean_matrix))
    return variance

In [20]:
#Calculate Covariance Matrix
def cal_covariance(a):
    '''
    Input : a is nxd numpy matrix
    Output : A covariance matrix of dimention dxd
    '''
    n,d = np.shape(a)
    mean_matrix = np.ones((n,d))*cal_mean(a)
    co_var = (1/(n-1)) * (np.transpose(a-mean_matrix).dot(a-mean_matrix))
    return co_var

In [11]:
#Calculate Mean
def cal_mean(a):
    '''
    Input : a is nxd numpy matrix
    Output : A mean vector of dimention d
    '''
    n,d = np.shape(a)
    #print(n,d)
    mean = np.sum(a,axis=0) / n
    return(mean)

In [26]:
#Calculate Kernel A given in Assignment
def kernel_A(x,y,d):
    temp = x.T.dot(y)
    return((1+temp)**d)

In [27]:
#Calculate Kernel B given in Assignment
def kernel_B(x,y,sigma):
    temp = (-1 * ((x-y).T.dot(x-y))) / (2*sigma**2)
    return(np.exp(temp))

In [ ]:
# Main function of PCA
def pca(x):
    pass

In [ ]:
# Main function of KPCA
def kpca(x):
    pass

In [25]:
if __name__ == "__main__":
    a=np.array([[1,2,3],[8,9,10],[-5,2,30]])
    print(cal_covariance(a))
    print(np.cov(a.T))
    print(3**2)

3 3
[[  42.33333333   23.33333333  -62.16666667]
 [  23.33333333   16.33333333  -15.16666667]
 [ -62.16666667  -15.16666667  196.33333333]]
[[  42.33333333   23.33333333  -62.16666667]
 [  23.33333333   16.33333333  -15.16666667]
 [ -62.16666667  -15.16666667  196.33333333]]
9
